services:
  - type: web
    name: trading-bot-webhook
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn webhook_server.main:app --host 0.0.0.0 --port 8000"
    plan: free
    envVars:
      - key: API_KEY
        value: tradingview_webhook_uk_bot
      - key: SECRET_KEY
        value: d4f0c532-3905-449f-b7da-69ee07125da7
      - key: BINANCE_API_KEY
        value: your_testnet_api_key
      - key: BINANCE_API_SECRET
        value: your_testnet_api_secret
      - key: USE_TESTNET
        value: true
      - key: SYMBOLS
        value: BNBUSDT,BTCUSDT,ETHUSDT
      - key: MAX_POSITION_SIZE
        value: 0.01
      - key: COOLDOWN_SECONDS
        value: 60
      - key: MAX_POSITION_SIZE_BNB
        value: 0.1
      - key: MAX_POSITION_SIZE_ETH
        value: 0.02
      - key: MAX_POSITION_SIZE_BTC
        value: 0.005
